@echo off
mkdir screen-share-app
mkdir screen-share-app\client
mkdir screen-share-app\client\public
mkdir screen-share-app\client\src
mkdir screen-share-app\client\src\components
mkdir screen-share-app\client\src\components\common
mkdir screen-share-app\client\src\components\common\Button
mkdir screen-share-app\client\src\components\common\Input
mkdir screen-share-app\client\src\components\common\Modal
mkdir screen-share-app\client\src\components\common\Loader
mkdir screen-share-app\client\src\components\host
mkdir screen-share-app\client\src\components\viewer
mkdir screen-share-app\client\src\components\layout
mkdir screen-share-app\client\src\hooks
mkdir screen-share-app\client\src\services
mkdir screen-share-app\client\src\utils
mkdir screen-share-app\client\src\types
mkdir screen-share-app\client\src\styles
mkdir screen-share-app\server
mkdir screen-share-app\server\src
mkdir screen-share-app\server\src\controllers
mkdir screen-share-app\server\src\services
mkdir screen-share-app\server\src\types
mkdir screen-share-app\server\src\utils
mkdir screen-share-app\server\src\middleware
mkdir screen-share-app\shared
mkdir screen-share-app\shared\types
mkdir screen-share-app\scripts
mkdir screen-share-app\docker
mkdir screen-share-app\.github
mkdir screen-share-app\.github\workflows
echo Directories created successfully.
